[scripts]
"#disabled" = "exit 1" # "commented" out
nop = ""
basic = "ls -la" # string
with_arg = "ls -h test" # call other task with args
no_error = "-with_arg" # suppress error
composite = ["no_error", "with_arg test/*.py"]

pdm1 = { cmd = "ls -la" } # basic command
pdm2 = { shell = "ls -la >/dev/null" } # supports redirection
pdm3 = { call = "ds:main" }
pdm4 = { composite = ["pdm1", "pdm2"] }
