# This example file demonstrates how `ds` handles loops.

[scripts]
# Simple string tasks cannot call other tasks, so this is not a loop.
ls = "ls" # => $ ls

# Composite tasks can pass parameters to tasks that have a different
# name than the parent. Otherwise, they're executed as a shell.
df = ["df"] # => $ df

ls2 = ["ls", "ls"]
