# This example file demonstrates how `ds` handles "bad" loops. In a true
# loop like this, none of the tasks will be executed until the loop is removed.

[scripts]
this = ["bad"]
bad = ["-loop"] # Error suppression won't help.
loop = ["this"]
